version: '3'

networks:
    db:
        external: true

volumes:
    redis-data:

services:
    redis:
        image: redis:6-alpine3.13
        container_name: redis
        volumes:
            - redis-data:/data
        networks:
            - db

    traefik:
        container_name: traefik
        image: traefik:v2.2
        labels:
            - traefik.enable=true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/traefik_dynamic.toml:/traefik_dynamic.toml
            - ./traefik/acme.json:/acme.json # be sure to chmod 600 acme.json
        networks:
            - db

    polkaview:
        build:
            context: .
            dockerfile: Dockerfile-prod
        image: polkaview:latest
        labels:
            - traefik.enable=true
            - traefik.http.routers.polkadot.rule=Host(`polkaview.network`, `treasuries.network`)
            - traefik.http.routers.polkadot.tls=true
            - traefik.http.routers.polkadot.tls.certresolver=lets-encrypt
            - traefik.http.routers.polkadot.middlewares=redirect-www@file

            - traefik.http.services.polkadot.loadbalancer.server.port=3000


            - traefik.http.middlewares.polkadot.headers.accesscontrolallowmethods=GET,OPTIONS,PUT
            - traefik.http.middlewares.polkadot.headers.accesscontrolalloworiginlist=https://polkaview.network
            - traefik.http.middlewares.polkadot.headers.accesscontrolmaxage=100
            - traefik.http.middlewares.polkadot.headers.addvaryheader=true


        container_name: polkaview
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - redis
        networks:
            - db
